<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Imaginary.Core\Imaginary.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RollForward>Major</RollForward>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
    <Using Remove="System.Drawing" />
  </ItemGroup>

  <PropertyGroup>
    <!-- Windows PE-Metadaten & Dateieigenschaften -->
    <AssemblyTitle>Imaginary</AssemblyTitle>
    <Title>Imaginary</Title>
    <Product>Imaginary</Product>
    <Description>Moderner Bild-Konverter, Optimierer &amp; Icon-Studio</Description>
    <Company>Pino Wackers</Company>
    <Authors>Pino Wackers</Authors>
    <Copyright>© 2026 Pino Wackers. Alle Rechte vorbehalten.</Copyright>
    <Version>2.2.5</Version>
    <AssemblyVersion>2.2.5.0</AssemblyVersion>
    <FileVersion>2.2.5.0</FileVersion>
    <InformationalVersion>2.2.5</InformationalVersion>
    <NeutralLanguage>de-DE</NeutralLanguage>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\**" />
    <Resource Include="app.ico" />
  </ItemGroup>

</Project>
